export { default as Conection } from "../Auth/Conection/Conection";
export { default as Calendar } from "./Calendar/Calendar";
export { default as Contact } from "./Contact/Contact";
export { default as Error404 } from "./Error404/Error404";
export { default as Home } from "./Home/Home";
export { default as Inscription } from "./Inscription/Inscription";
export { default as Localisation } from "./Localisation/Localisation";
export { default as Search } from "./Search/Search";
export { default as Zone } from "./Zone/Zone";
